COVID_FILE_PATH = "data/covidquex_256.npz"
COVID_IN_CHANNELS = 1
COVID_OUT_CHANNELS = 1

CELLNUCLEI_FILE_PATH = "data/cellnuclei_256.npz"
CELLNUCLEI_IN_CHANNELS = 3
CELLNUCLEI_OUT_CHANNELS = 1

NUSET_FILE_PATH = "data/NUSET_256.npz"
NUSET_IN_CHANNELS = 1
NUSET_OUT_CHANNELS = 1
